"""AIOS console runtime lifecycle, independent of canonical AI_SERVICE binding."""

VERSION = "0.1.0"
ERRORS = frozenset({
    "UNSUPPORTED_PLATFORM", "INVALID_ACTION", "INVALID_STATE_DIRECTORY", "STATE_CORRUPT",
    "STATE_IO", "ALREADY_RUNNING", "START_IN_PROGRESS", "START_FAILED", "START_TIMEOUT",
    "SERVICE_UNREACHABLE", "STALE_INSTANCE", "PROCESS_NOT_RUNNING", "PEER_MISMATCH",
    "PROTOCOL_ERROR", "STOP_TIMEOUT", "STOP_FAILED", "PIDFD_UNAVAILABLE",
    "OBSERVATION_FAILED", "BOOT_FAILED", "INTERNAL_ERROR", "GENERATION_EXHAUSTED", "BUSY",
})
